development:
      host: localhost
      adapter: mysql
      database: fedena_development
      port: 3306
      username: fedena
      password: 'arunlobo10'

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: fedena
      password: 'arunlobo10'

production:
      host: localhost
      adapter: mysql
      database: fedena_production21
      port: 3306
      username: fedena
      password: 'arunlobo10'
cucumber:
  <<: *test
